CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price BIGINT NOT NULL,
  currency_code CHAR(3) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  quantity INT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  url_slug VARCHAR(255),
  category_id BIGINT REFERENCES category(id),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE product_picture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  position INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  product_id BIGINT REFERENCES product(id) ON DELETE CASCADE NOT NULL,
  UNIQUE (product_id, position)
);
